import { expect, type APIRequestContext, type Page } from '@playwright/test'

const BACKEND_ORIGIN = process.env.E2E_BACKEND_URL ?? 'http://127.0.0.1:8000'
const API_URL = `${BACKEND_ORIGIN}/api`

interface AuthPayload {
  access_token: string
  token_type: string
  user: {
    id: number
    email: string
    full_name: string | null
    created_at: string
  }
}

interface ProjectPayload {
  id: number
  name: string
}

interface ChartPayload {
  id: number
  name: string
  chart_version: string
}

export async function ensureBackendHealthy(request: APIRequestContext) {
  const response = await request.get(`${BACKEND_ORIGIN}/health`)
  expect(response.ok()).toBeTruthy()
}

export async function authenticateViaApi(page: Page, request: APIRequestContext) {
  const email = `helmgen-e2e-${Date.now()}-${Math.floor(Math.random() * 10000)}@example.com`
  const password = 'playwright-pass-123'

  const registerResponse = await request.post(`${API_URL}/auth/register`, {
    data: {
      email,
      password,
      full_name: 'Playwright User',
    },
  })

  expect(registerResponse.ok()).toBeTruthy()
  const auth = await registerResponse.json() as AuthPayload

  await page.addInitScript(([token, user]) => {
    window.localStorage.setItem('helmgen-token', token)
    window.localStorage.setItem('helmgen-user', JSON.stringify(user))
  }, [auth.access_token, auth.user] as const)

  return auth
}

export async function seedChartFixture(request: APIRequestContext, token: string) {
  const headers = {
    Authorization: `Bearer ${token}`,
  }

  const projectResponse = await request.post(`${API_URL}/projects/`, {
    headers,
    data: {
      name: `e2e-project-${Date.now()}`,
      description: 'Playwright seeded project',
    },
  })
  expect(projectResponse.ok()).toBeTruthy()
  const project = await projectResponse.json() as ProjectPayload

  const valuesYaml = [
    'replicaCount: 2',
    'image:',
    '  repository: nginxinc/nginx-unprivileged',
    '  tag: 1.27.5-alpine',
    'service:',
    '  enabled: true',
    '  type: ClusterIP',
    '  port: 8080',
  ].join('\n')

  const chartResponse = await request.post(`${API_URL}/charts/`, {
    headers,
    data: {
      project_id: project.id,
      name: `e2e-chart-${Date.now()}`,
      description: 'Generated by Playwright',
      chart_version: '0.1.0',
      app_version: '1.27.5-alpine',
      values_yaml: valuesYaml,
    },
  })
  expect(chartResponse.ok()).toBeTruthy()
  const chart = await chartResponse.json() as ChartPayload

  const generateResponse = await request.post(`${API_URL}/charts/${chart.id}/generate`, {
    headers,
    data: {
      values_yaml: valuesYaml,
    },
  })
  expect(generateResponse.ok()).toBeTruthy()

  return { project, chart }
}
